**Exercise 1.2**
This exercise involves the Auto data set available as Auto.csv from the website for the main course textbook James et al. http://www-bcf.usc.edu/~gareth/ISL/data.html. Make sure that the missing values have been removed from the data. You should load that dataset as the first step of the exercise.

In [1]:
df <-read.csv("Auto.csv")
View(df)
str(df)

    mpg cylinders displacement horsepower weight acceleration year origin
1   18  8         307          130        3504   12.0         70   1
2   15  8         350          165        3693   11.5         70   1
3   18  8         318          150        3436   11.0         70   1
4   16  8         304          150        3433   12.0         70   1
5   17  8         302          140        3449   10.5         70   1
6   15  8         429          198        4341   10.0         70   1
7   14  8         454          220        4354    9.0         70   1
8   14  8         440          215        4312    8.5         70   1
9   14  8         455          225        4425   10.0         70   1
10  15  8         390          190        3850    8.5         70   1
11  15  8         383          170        3563   10.0         70   1
12  14  8         340          160        3609    8.0         70   1
13  15  8         400          150        3761    9.5         70   1
14  14  8         455          225        3086   10.0         70   1
15  24  4         113          95         2372   15.0         70   3
16  22  6         198          95         2833   15.5         70   1
17  18  6         199          97         2774   15.5         70   1
18  21  6         200          85         2587   16.0         70   1
19  27  4          97          88         2130   14.5         70   3
20  26  4          97          46         1835   20.5         70   2
21  25  4         110          87         2672   17.5         70   2
22  24  4         107          90         2430   14.5         70   2
23  25  4         104          95         2375   17.5         70   2
24  26  4         121          113        2234   12.5         70   2
25  21  6         199          90         2648   15.0         70   1
26  10  8         360          215        4615   14.0         70   1
27  10  8         307          200        4376   15.0         70   1
28  11  8         318          210        4382   13.5         70   1
29   9  8         304          193        4732   18.5         70   1
30  27  4          97          88         2130   14.5         71   3
⋮   ⋮   ⋮         ⋮            ⋮          ⋮      ⋮            ⋮    ⋮
368 28  4         112          88         2605   19.6         82   1
369 27  4         112          88         2640   18.6         82   1
370 34  4         112          88         2395   18.0         82   1
371 31  4         112          85         2575   16.2         82   1
372 29  4         135          84         2525   16.0         82   1
373 27  4         151          90         2735   18.0         82   1
374 24  4         140          92         2865   16.4         82   1
375 36  4         105          74         1980   15.3         82   2
376 37  4          91          68         2025   18.2         82   3
377 31  4          91          68         1970   17.6         82   3
378 38  4         105          63         2125   14.7         82   1
379 36  4          98          70         2125   17.3         82   1
380 36  4         120          88         2160   14.5         82   3
381 36  4         107          75         2205   14.5         82   3
382 34  4         108          70         2245   16.9         82   3
383 38  4          91          67         1965   15.0         82   3
384 32  4          91          67         1965   15.7         82   3
385 38  4          91          67         1995   16.2         82   3
386 25  6         181          110        2945   16.4         82   1
387 38  6         262          85         3015   17.0         82   1
388 26  4         156          92         2585   14.5         82   1
389 22  6         232          112        2835   14.7         82   1
390 32  4         144          96         2665   13.9         82   3
391 36  4         135          84         2370   13.0         82   1
392 27  4         151          90         2950   17.3         82   1
393 27  4         140          86         2790   15.6         82   1
394 44  4          97          52         2130   24.6         82   2
395 32  4         135          84         2295   11.6         82   1
396 28  4         120          79         2625   18.6         82   1
397 31  4         119          82         2720   19.4         82   1
    name
1   chevrolet chevelle malibu
2   buick skylark 320
3   plymouth satellite
4   amc rebel sst
5   ford torino
6   ford galaxie 500
7   chevrolet impala
8   plymouth fury iii
9   pontiac catalina
10  amc ambassador dpl
11  dodge challenger se
12  plymouth 'cuda 340
13  chevrolet monte carlo
14  buick estate wagon (sw)
15  toyota corona mark ii
16  plymouth duster
17  amc hornet
18  ford maverick
19  datsun pl510
20  volkswagen 1131 deluxe sedan
21  peugeot 504
22  audi 100 ls
23  saab 99e
24  bmw 2002
25  amc gremlin
26  ford f250
27  chevy c20
28  dodge d200
29  hi 1200d
30  datsun pl510
⋮   ⋮
368 chevrolet cavalier
369 chevrolet cavalier wagon
370 chevrolet cavalier 2-door
371 pontiac j2000 se hatchback
372 dodge aries se
373 pontiac phoenix
374 ford fairmont futura
375 volkswagen rabbit l
376 mazda glc custom l
377 mazda glc custom
378 plymouth horizon miser
379 mercury lynx l
380 nissan stanza xe
381 honda accord
382 toyota corolla
383 honda civic
384 honda civic (auto)
385 datsun 310 gx
386 buick century limited
387 oldsmobile cutlass ciera (diesel)
388 chrysler lebaron medallion
389 ford granada l
390 toyota celica gt
391 dodge charger 2.2
392 chevrolet camaro
393 ford mustang gl
394 vw pickup
395 dodge rampage
396 ford ranger
397 chevy s-10

'data.frame':	397 obs. of  9 variables:
 $ mpg         : num  18 15 18 16 17 15 14 14 14 15 ...
 $ cylinders   : int  8 8 8 8 8 8 8 8 8 8 ...
 $ displacement: num  307 350 318 304 302 429 454 440 455 390 ...
 $ horsepower  : chr  "130" "165" "150" "150" ...
 $ weight      : int  3504 3693 3436 3433 3449 4341 4354 4312 4425 3850 ...
 $ acceleration: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
 $ year        : int  70 70 70 70 70 70 70 70 70 70 ...
 $ origin      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ name        : chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...

In [2]:
#Check for missing vals
colSums(is.na(df))

         mpg    cylinders displacement   horsepower       weight acceleration
           0            0            0            0            0            0
        year       origin         name
           0            0            0

**a. Which of the predictors are quantitative, and which are qualitative?**

Qualitative variables are: name, Year, Origin

Quantitative: cylinders, mpg, displacement, horsepower, weight, acceleration

In [3]:
#For convinience we are going to change the type of variables to numeric instead
#of int

df$cylinders <- as.numeric(df$cylinders)
df$horsepower <- as.numeric(df$horsepower )
df$year <- as.factor(df$year)
df$weight <- as.numeric(df$weight)
df$origin <- as.factor(df$origin)

str(df)

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

'data.frame':	397 obs. of  9 variables:
 $ mpg         : num  18 15 18 16 17 15 14 14 14 15 ...
 $ cylinders   : num  8 8 8 8 8 8 8 8 8 8 ...
 $ displacement: num  307 350 318 304 302 429 454 440 455 390 ...
 $ horsepower  : num  130 165 150 150 140 198 220 215 225 190 ...
 $ weight      : num  3504 3693 3436 3433 3449 ...
 $ acceleration: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
 $ year        : Factor w/ 13 levels "70","71","72",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ origin      : Factor w/ 3 levels "1","2","3": 1 1 1 1 1 1 1 1 1 1 ...
 $ name        : chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...

In [4]:
#Check for missing data again
colSums(is.na(df))

         mpg    cylinders displacement   horsepower       weight acceleration
           0            0            0            5            0            0
        year       origin         name
           0            0            0

In [6]:
#Eliminate the missing data
new_df <- na.omit(df)

In [7]:
colSums(is.na(new_df))

         mpg    cylinders displacement   horsepower       weight acceleration
           0            0            0            0            0            0
        year       origin         name
           0            0            0

In [8]:
View(new_df)

    mpg cylinders displacement horsepower weight acceleration year origin
1   18  8         307          130        3504   12.0         70   1
2   15  8         350          165        3693   11.5         70   1
3   18  8         318          150        3436   11.0         70   1
4   16  8         304          150        3433   12.0         70   1
5   17  8         302          140        3449   10.5         70   1
6   15  8         429          198        4341   10.0         70   1
7   14  8         454          220        4354    9.0         70   1
8   14  8         440          215        4312    8.5         70   1
9   14  8         455          225        4425   10.0         70   1
10  15  8         390          190        3850    8.5         70   1
11  15  8         383          170        3563   10.0         70   1
12  14  8         340          160        3609    8.0         70   1
13  15  8         400          150        3761    9.5         70   1
14  14  8         455          225        3086   10.0         70   1
15  24  4         113           95        2372   15.0         70   3
16  22  6         198           95        2833   15.5         70   1
17  18  6         199           97        2774   15.5         70   1
18  21  6         200           85        2587   16.0         70   1
19  27  4          97           88        2130   14.5         70   3
20  26  4          97           46        1835   20.5         70   2
21  25  4         110           87        2672   17.5         70   2
22  24  4         107           90        2430   14.5         70   2
23  25  4         104           95        2375   17.5         70   2
24  26  4         121          113        2234   12.5         70   2
25  21  6         199           90        2648   15.0         70   1
26  10  8         360          215        4615   14.0         70   1
27  10  8         307          200        4376   15.0         70   1
28  11  8         318          210        4382   13.5         70   1
29   9  8         304          193        4732   18.5         70   1
30  27  4          97           88        2130   14.5         71   3
⋮   ⋮   ⋮         ⋮            ⋮          ⋮      ⋮            ⋮    ⋮
368 28  4         112           88        2605   19.6         82   1
369 27  4         112           88        2640   18.6         82   1
370 34  4         112           88        2395   18.0         82   1
371 31  4         112           85        2575   16.2         82   1
372 29  4         135           84        2525   16.0         82   1
373 27  4         151           90        2735   18.0         82   1
374 24  4         140           92        2865   16.4         82   1
375 36  4         105           74        1980   15.3         82   2
376 37  4          91           68        2025   18.2         82   3
377 31  4          91           68        1970   17.6         82   3
378 38  4         105           63        2125   14.7         82   1
379 36  4          98           70        2125   17.3         82   1
380 36  4         120           88        2160   14.5         82   3
381 36  4         107           75        2205   14.5         82   3
382 34  4         108           70        2245   16.9         82   3
383 38  4          91           67        1965   15.0         82   3
384 32  4          91           67        1965   15.7         82   3
385 38  4          91           67        1995   16.2         82   3
386 25  6         181          110        2945   16.4         82   1
387 38  6         262           85        3015   17.0         82   1
388 26  4         156           92        2585   14.5         82   1
389 22  6         232          112        2835   14.7         82   1
390 32  4         144           96        2665   13.9         82   3
391 36  4         135           84        2370   13.0         82   1
392 27  4         151           90        2950   17.3         82   1
393 27  4         140           86        2790   15.6         82   1
394 44  4          97           52        2130   24.6         82   2
395 32  4         135           84        2295   11.6         82   1
396 28  4         120           79        2625   18.6         82   1
397 31  4         119           82        2720   19.4         82   1
    name
1   chevrolet chevelle malibu
2   buick skylark 320
3   plymouth satellite
4   amc rebel sst
5   ford torino
6   ford galaxie 500
7   chevrolet impala
8   plymouth fury iii
9   pontiac catalina
10  amc ambassador dpl
11  dodge challenger se
12  plymouth 'cuda 340
13  chevrolet monte carlo
14  buick estate wagon (sw)
15  toyota corona mark ii
16  plymouth duster
17  amc hornet
18  ford maverick
19  datsun pl510
20  volkswagen 1131 deluxe sedan
21  peugeot 504
22  audi 100 ls
23  saab 99e
24  bmw 2002
25  amc gremlin
26  ford f250
27  chevy c20
28  dodge d200
29  hi 1200d
30  datsun pl510
⋮   ⋮
368 chevrolet cavalier
369 chevrolet cavalier wagon
370 chevrolet cavalier 2-door
371 pontiac j2000 se hatchback
372 dodge aries se
373 pontiac phoenix
374 ford fairmont futura
375 volkswagen rabbit l
376 mazda glc custom l
377 mazda glc custom
378 plymouth horizon miser
379 mercury lynx l
380 nissan stanza xe
381 honda accord
382 toyota corolla
383 honda civic
384 honda civic (auto)
385 datsun 310 gx
386 buick century limited
387 oldsmobile cutlass ciera (diesel)
388 chrysler lebaron medallion
389 ford granada l
390 toyota celica gt
391 dodge charger 2.2
392 chevrolet camaro
393 ford mustang gl
394 vw pickup
395 dodge rampage
396 ford ranger
397 chevy s-10